[package]
name = "eclair_bindings_derive"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.50"
quote = "1.0.23"
syn = "1.0.107"

[dev-dependencies]
eclair_bindings = { path = "../eclair_bindings" }
