[package]
name = "eclair_bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffi-opaque = "2.0.1"
libc = "0.2.139"
